
import "./globals.css";
import "./globals.scss";


// import Header from "@/components/Header";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/toaster";


// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export const metadata = {
  other: {
    google: "notranslate",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider appearance={{ variables: { colorPrimary: "#06b6d4" } }}>
      <html lang="en" className="notranslate" translate="no">
        <body translate="no">{children}</body>
        <Toaster />
      </html>
    </ClerkProvider>
  );
}
