import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import DashboardRouterProvider from "@/components/Nav/DashboardRouterContext";
import Navbar from "@/components/Nav/DashboardNav"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DashboardRouterProvider>
          <Navbar documents={[]}>{children}</Navbar>
        </DashboardRouterProvider>
      </body>
    </html>
  );
}
